export { default as Home } from './Home'
export { default as Artist } from './Artist'
export { default as Search } from './Search'
export { default as Collection } from './Collection'
export { default as Playlist } from './Playlist'
export { default as ErrorPage } from './ErrorPage'